HellProject/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from HellProject import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_info.urls'), name = 'user_info'),
    path('listview/', include('list.urls'), name='list'),
    path('inquiry/', include('inquiry.urls'), name='inquiry'),
    path('market/', include('market.urls'), name='market'),
]
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inquiry/urls.py
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'inquiry'

urlpatterns=[
    path('CS/', views.CS, name = 'CS'),
    path('FAQ/', views.FAQ, name = 'FAQ'),
]

list/urls.py
from django.urls import path
from django.conf.urls.static import static

from HellProject import settings
from . import views

app_name = 'list'

urlpatterns =[
    path('list_view/', views.list_view, name='list_view'),

    path('helpWrite/', views.helpWrite, name='helpWrite'),
    path('helpUpdate/<str:id>', views.helpUpdate, name='helpUpdate'),
    path('helpDelete/<str:id>', views.helpDelete, name='helpDelete'),
    
    path('feed_Deatil/<str:id>', views.feed_Detail, name='feed_Detail'),
    path('donate/<str:id1>/<str:id2>/<str:id3>', views.donate, name='donate'),
]

market/urls.py
from django.urls import path
from django.conf.urls.static import static

from HellProject import settings
from . import views

app_name = 'market'

urlpatterns =[
    path('', views.market_view, name='market_view'),
    path('marketDetail/<str:id>', views.market_Detail, name='market_Detail'),
    path('marketWrite/', views.market_Write, name='market_Write'),
    path('marketDelete/<str:id>', views.market_Delete, name='market_Delete'),
    path('marketUpdate/<str:id>',views.market_Update, name='market_Update'),
    path('comment/<str:id>',views.comment, name='comment'),
]

user_info/urls.py
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'user_info'

urlpatterns=[
    path('', views.home, name = 'home'),
    path('mypage', views.mypage, name = 'mypage'),
    path('login', views.login_view, name = 'login_view'),
    path('signup', views.signup, name = 'signup'),
    path('logout_view/', views.logout_view, name="logout_view"),
    path('findID/', views.findID, name='findID'),
    path('delete/', views.delete, name = 'delete'),
    path('spon_delete/',views.spon_delete, name="spon_delete"),
    path('registerauth/', views.get_success_url, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),

    path('recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),

    path('profile_view/', views.profile_view, name='profile_view'),
    path('profile_update_view/', views.profile_update_view, name='profile_update_view'),
    path('verify/', views.verify, name='verify'),
    path('sponserpage/', views.sponserpage, name="sponserpage"),

    path('recentView/<str:email>', views.recentView, name="recentView"),
    path('recentDetail/<str:id>', views.recentDetail, name='recentDetail'),
    path('recentWrite/', views.recentWrite, name="recentWrite"),
    path('recentWriteUpdate/<str:id>', views.recentWriteUpdate, name="recentWriteUpdate"),
    path('recentDelete/<str:id>', views.recentDelete, name="recentDelete"),    
]

user_info/forms.py
from django import forms
from .models import Post1

class PostForm(forms.ModelForm):
    class Meta:
        model = Post1
        fields = ['title', 'body']

class RecoveryIdForm(forms.Form):
    phone = forms.CharField(
        widget=forms.TextInput,
    )
    class Meta:
        fields = ['phone']

    def __init__(self, *args, **kwargs):
        super(RecoveryIdForm, self).__init__(*args, **kwargs)
        self.fields['phone'].label = '휴대전화번호'
        self.fields['phone'].widget.attrs.update({
            # 'placeholder': '이름을 입력해주세요',
            'class': 'form-control',
            'id': 'form_phone',
        })

class RecoveryPwForm(forms.Form):
    email = forms.EmailField(
        widget=forms.EmailInput,)

    class Meta:
        fields = ['email']

    def __init__(self, *args, **kwargs):
        super(RecoveryPwForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = '이메일'
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'id': 'pw_form_email',
        })

from django.contrib.auth.forms import SetPasswordForm

class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(CustomSetPasswordForm, self).__init__(*args, **kwargs)
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
        })

user_info/views.py
import re
from django.core.exceptions import PermissionDenied, ValidationError
from user_info import verifing
from django.core import paginator
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone  # pub_date를 위해 import
from django.contrib import auth, messages
from .models import UserInfo, CustomUser, whodonate, Post1
from .forms import CustomSetPasswordForm, PostForm, RecoveryIdForm, RecoveryPwForm
from .GoogleApi import google_api
from list.models import Post
from django.views.decorators.csrf import csrf_exempt
from .verifing import ggoo


from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.auth.tokens import default_token_generator

import os

def home(request):
    msg =""
    if not request.user.is_authenticated:
        return render(request, 'index.html', {'msg': msg})
    real_user = UserInfo.objects.get(user_email=request.user.email)   
    return render(request, 'index.html', {'msg':msg, 'qua':str(real_user.qua)})

def findID(request):
    msg = ""
    if request.method == 'POST':
        phone = request.POST.get('phone')
        try:
            user = UserInfo.objects.get(user_phone = phone)
            msg = user.user_email
        except:
            msg = "error"
        return render(request, 'findID.html', {'msg':msg})
    return render(request, 'findID.html')


def login_view(request):


    if request.method == 'POST':
        username = request.POST["userid"]
        password = request.POST["userpw"]
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('user_info:home')
        else:
            msg = "error"
            return render(request, 'login.html', {'msg':msg})
    else:
        msg =""
        return render(request, 'login.html', {'msg':msg})

num1 = 0


@csrf_exempt
def signup(request):
    msg =""
    global num1

    num1 += 1

    if request.method == "POST":
        
        try:
            if CustomUser.objects.get(email=request.POST['user_email']):
                return render(request, 'signup.html', {"error" : "error", "num" : num1})
        except:
            pass
        
        if request.POST["user_pw1"] == request.POST["user_pw2"]:
            user = CustomUser.objects.create_user(
                email=request.POST['user_email'], password=request.POST['user_pw1'])
            auth.login(request, user)
            user_contents = UserInfo()
            user_contents.user_email = request.POST['user_email']
            user_contents.user_nickname = request.POST['user_nickname']
            user_contents.user_phone = request.POST['user_num']
            user_contents.user_name = request.POST['user_name']
            user_contents.user_account = request.POST['user_acname']
            user_contents.user_account_name = request.POST['user_acnum']
            user_contents.save()
            msg = "signup_success_but_email"
            return render(request, 'index.html', {'msg': msg , "num" : num1})
        msg = "NOTSAME_PW"
        return render(request, 'signup.html', {'msg':msg, "num" : num1})
    return render(request, 'signup.html', {"num" : num1})

def delete(request):
    user = CustomUser.objects.get(email=request.user.email)
    user_info = UserInfo.objects.get(user_email = user.email)
    auth.logout(request)
    user_info.delete()
    user.delete()
    msg = "delete_success"
    return render(request, 'index.html', {'msg':msg})

def get_success_url(request):
    msg="sending"
    user = UserInfo.objects.get(user_email=request.user.email)
    send_mail(
        '[WhoWant] {}님의 회원가입 인증메일 입니다.'.format(user.user_name),
            [user.user_email],
            html=render_to_string('register_email.html', {
                'user': request.user,
                'uid': urlsafe_base64_encode(force_bytes(request.user)).encode().decode(),
                'domain': request.META['HTTP_HOST'],
                'token': default_token_generator.make_token(request.user),
            }),
    )
    return render(request, 'index.html', {'msg':msg})
#유저 메일 활성화
def activate(request, uid64, token):
    msg = ""
    try:
        uid = force_text(urlsafe_base64_decode(uid64))
        print(uid)
        current_user = CustomUser.objects.get(email=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
        msg = "activate_error"
        return render(request, 'index.html', {'msg': msg})
    msg = "token_error"
    if default_token_generator.check_token(current_user, token):
        current_user.active = True
        current_user.save()
        msg = "email_success"
    return render(request, 'index.html', {'msg': msg})

def verify(request):
    if request.method=='POST':
        img = request.FILES.get('image')
        if img:
            img = img.read()
        else:
            msg = "fail"
            return render(request, 'index.html', {'msg':msg})

            
        user = CustomUser.objects.get(email=request.user)
        real_user = UserInfo.objects.get(user_email=request.user.email)
        msg = ""
        if ggoo(img,real_user.user_name):
            real_user.qua = 'yes'
            real_user.save()
            msg = "success"
        else:
            msg = "fail"
    return render(request, 'index.html', {'msg':msg})

def logout_view(request):
    auth.logout(request)
    return redirect('user_info:home')

def mypage(request):
    if not request.user.is_authenticated:
        msg = "Do Login"
        return render(request, "mypage.html", {'msg':msg})
    user = CustomUser.objects.get(email=request.user.email)
    userinfo = UserInfo.objects.get(user_email=user)
    #돈을 준 사람이 현재 유저인 사람과 같을때, 그니까 현재 유저한테 후원받은사람들 필터링
    my_donate_relation = whodonate.objects.filter(whogivemoney=request.user.email)
    #거기서 중복 제거
    mdr = my_donate_relation.values_list('whogetmoney', flat=True).distinct()
    my_receiver = []
    msg = ""
    for m in mdr:
        my_receiver.append(UserInfo.objects.get(user_email=m))


    if userinfo.qua == "yes":
        return redirect('user_info:sponserpage')
    if request.method == 'POST':
        money = request.POST['mine']
        try:
            money = int(money)
        except:
            msg = "failed"
            return render(request, 'mypage.html', {"error" : msg})

        save_money = int(userinfo.cash)
        userinfo.cash = money + save_money
        userinfo.user_totalcash += money
        userinfo.save()
        msg = "success"
    return render(request, 'mypage.html', {"userinfo" : userinfo ,"money" : userinfo.cash,"success":msg ,'receivers':my_receiver ,"temperature" : str(round(0.1 * (userinfo.user_totaldonate / 1000),2))})

def recentDetail(request, id):
    post = Post1.objects.get(id=id)
    return render(request, 'recentDetail.html', {'post':post})

def recentWrite(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.post_time = timezone.now()
            image = request.FILES.get('image')
            
            if image:
                img = request.FILES.get('image').read()
                if google_api(img):
                    post.photo=image
                    post.save()
                    return redirect('user_info:sponserpage')
                else:
                    return render(request, 'recentWrite.html', {"error" : "error"})
        post.save()
        return redirect('user_info:sponserpage')
    return render(request, 'recentWrite.html')

def recentWriteUpdate(request, id):
    post = Post1.objects.get(id=id)
    whos = whodonate.objects.filter(whogetmoney=request.user)
    posts = Post.objects.filter(writer=request.user).order_by('-post_time')
    recent_posts = Post1.objects.filter(writer=request.user).order_by('-post_time')
    user_profile = UserInfo.objects.get(user_email = request.user)
    msg = ""
    if request.method == 'POST':
        post.title = request.POST['title']
        post.body = request.POST['body']
        image = request.FILES.get('image')
        if image:
            img = request.FILES.get('image').read()
            if google_api(img):
                post.photo=image
                post.save()
                return redirect('user_info:sponserpage')
            else:          
                return render(request, 'recentWrite.html', {"error" : "error"})
        post.save()
        msg = "update_success"
        return render(request, 'sponserpage.html', {'whos' : whos, 'posts': posts, 'recent_posts':recent_posts , 'user_profile':user_profile, 'msg':msg})
    return render(request, 'recentWriteUpdate.html', {'post':post})

def recentDelete(request, id):
    post = Post1.objects.get(id=id)
    post.delete()
    return redirect('user_info:sponserpage')
from django.core.paginator import Paginator

def spon_delete(request):
    user = CustomUser.objects.get(email = request.user.email)
    whos = whodonate.objects.filter(whogetmoney=user)
    user_info = UserInfo.objects.get(user_email=request.user.email)
    for who in whos:
        who.delete()
    auth.logout(request)
    user_info.delete()
    user.delete()
    msg = 'spon_delete'
    return render(request, 'index.html', {'msg':msg})

def sponserpage(request):
    msg = ""
    user = CustomUser.objects.get(email=request.user.email)
    whos = whodonate.objects.filter(whogetmoney=user)
    posts = Post.objects.filter(writer=request.user)
    paginator = Paginator(posts, 8)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    user_profile = UserInfo.objects.get(user_email = request.user)

user_info/templates/mypage.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--    <link rel="stylesheet" type="text/css" href="{% static 'mypage.css' %}">-->
    <link rel="stylesheet" type="text/css" href="{% static 'mypage.css'%}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.4.1/dist/chart.min.js"></script>
    <script language='javascript'>

    function noEvent() {
        if (event.keyCode == 116) {
            event.keyCode= 2;
            return false;
        }
        else if(event.ctrlKey && (event.keyCode==78 || event.keyCode == 82))
        {
            return false;
        }
    }
    document.onkeydown = noEvent;
    
    </script>
    <title>후원을 다이렉트로, 후원트</title>
</head>
<body oncontextmenu="return false">
    {% if msg == "Do Login" %}
    <script>
        alert("로그인 후 이용해주세요");
        window.location.href = "{% url 'user_info:login_view' %}";
    </script>
    {% endif %}
    {% if error == "failed" %}
    <script>
        alert("올바른 금액을 작성해주세요.");
    </script>
    {% endif %}
    {% if success == "success" %}
    <script>
        alert("충전에 성공하였습니다.");
    </script>
    {% endif %}
<div class="header">
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
        <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
        <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>
<div class="contentBox">
    <div class="userProfile">
        <div class="topBox">
            <button class="writeBtn hidden">프로필 변경</button>
            <!--        <i class="fa fa-user-circle-o" aria-hidden="true"></i>-->
            {% if userinfo.user_image %}
            <img src="{{userinfo.user_image.url}}" class="userImg">
            {% else %}
            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
            {% endif %}
            <div class="verticalTextBox">
                <button class="writeBtn" type="button" onclick="location.href = '{% url 'user_info:profile_view'%}';">
                    프로필 변경
                </button>
                <button class="writeBtn" type="button" onclick="location.href = '{% url 'user_info:delete'%}';">회원 탈퇴
                </button>
            </div>
        </div>
        {% if not user.active %}
        <button class="writeBtn" type="button" onclick="location.href = '{% url 'user_info:register_success' %}';">이메일
            인증
        </button>
        {% endif %}

        <h3>{{userinfo.user_email}}</h3>
    </div>
    <div class="horizontalBox">
        <div class="pointBox">
            <div class="titleBox">
                <i class="fa fa-credit-card-alt" aria-hidden="true"></i>
                <div class="titleText">
                    <h2>당신의 보유 포인트</h2>
                    {% if money is 0 %}
                    <h3>금액이 하나도 없어요!</h3>
                    {% else %}
                    <h3>{{money}}</h3>
                    {% endif %}
                </div>
            </div>
            <form action="{% url 'user_info:mypage' %}" method="POST">
                {% csrf_token %}
                <div class="inputArea">
                    <input type="number" placeholder="금액 입력" name="mine" class="pointInput">
                    <button input="submit">충전하기</button>
                </div>
            </form>
        </div>
        <div class="tempBox">
            <div class="titleBox">
                <i class="fa fa-thermometer-empty" aria-hidden="true"></i>
                <div class="titleText">
                    <h2>당신의 마음의 온도는 </h2>
                    <h3>{{temperature}}℃</h3>
                </div>
            </div>
            <div class="inputArea">
                <button type="button" onclick="location.href = '{% url 'list:list_view' %}' ">후원하러 가기</button>
            </div>
        </div>
    </div>
    <h2>내가 후원했던 사람 어떻게 살고있을까??</h2>

    <div class="donateList">
        <div class="swiper-container mySwiper">
            <div class="swiper-wrapper">
                {% for receiver in receivers %}
                <div class="swiper-slide">
                    <h2>{{receiver.user_nickname}}</h2>
                    {% if receiver.user_image %}
                    <img src="{{receiver.user_image.url}}">
                    {% else %}
                    <img src="{% static 'img/original.png' %}"
                         {% endif %}
                    <h3>{{receiver.user_description}}</h3>
                    <button type="button"
                            onclick="location.href = '{% url 'user_info:recentView' receiver.user_email %}'">근황보기
                    </button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

</div>

<div class="footer">
    <ul>
        <li><a href="#" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="#" class="navItem">기업소개</a></li>
        <li><a href="#" class="navItem">이용약관</a></li>
        <li><a href="#" class="navItem">개인정보 처리방침</a></li>
        <li><a href="#" class="navItem">고객센터</a></li>
    </ul>
    <span class="line"></span>
    <h2>(주)후원트 (대표이사:후대표) | 대구광역시 수성구 범어천로20 두산위브더제니스 4202호 | 통신판매번호 : 00-00-00-00
        유료직업소개사업등록번호 : (국내) 제000-00000-00000 | (국외) 000-0000-0000 | 사업자등록번호 : 0000-0000-0000
        © WhoWantLab, Inc.</h2>
</div>

<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script>
    var swiper = new Swiper(".mySwiper", {
        slidesPerView: 3,
        spaceBetween: 30,
        freeMode: true,

    });
</script>
</body>

user_info/templates/sponserpage.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'sponserpage.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.4.1/dist/chart.min.js"></script>
    <title>후원을 다이렉트로, 후원트</title>
</head>
<body>
{% if msg == 'update_success' %}
<script>
    alert("글 수정 성공!")
    window.location.href = "{% url 'user_info:sponserpage' %}"
</script>
{% endif %}
<div class="header">
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
        <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
        <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>
<div class="contentBox">
    <div class="profileAndDonate">
        <div class="userProfile">
            <div class="topBox">
                <button class="writeBtn hidden">프로필 변경</button>
                <!--        <i class="fa fa-user-circle-o" aria-hidden="true"></i>-->
                {% if user_profile.user_image %}
                <img src="{{user_profile.user_image.url}}">
                {% else %}
                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                {% endif %}
                {% if not user.active %}
                <button class="writeBtn" type="button"
                        onclick="location.href = '{% url 'user_info:register_success' %}';">이메일 인증
                </button>
                {% endif %}
                <div class="verticalTextBox">
                    <button class="writeBtn" type="button"
                            onclick="location.href = '{% url 'user_info:profile_view'%}';">
                        프로필 변경
                    </button>
                    <button class="writeBtn" type="button"
                            onclick="location.href = '{% url 'user_info:spon_delete'%}';">회원
                        탈퇴
                    </button>
                </div>
            </div>
            <h3>{{user_profile.user_email}}</h3>
            <h5 class="email">{{user_profile.user_description}}</h5>
        </div>
        <div class="donateHistory">
            <div class="titleBox">
                <i class="fa fa-credit-card-alt" aria-hidden="true"></i>
                <h2>후원받은 내역</h2>
            </div>
            <div class="historyBox">
                {% for who in whos %}
                <div class="horizontalBox">
                    <h2>{% if who.created_string == False %}
                        {{who.created|date:'m월 d일'}}
                        {% else %}
                        {{who.created_string}}
                        {% endif %}</h2>
                    <h2>{{ who.whogivemoney }}</h2>
                    <h2>{{ who.givemoney }}원</h2>
                </div>
                {% endfor %}
            </div>


        </div>
    </div>
</div>
<div class="writeList">
    <div class="hTitleBox">
        <h2>후원 게시글</h2>
        <button type="button" class="writeBtn" onclick="location.href = '{% url 'list:helpWrite'%}';">작성하기</button>
    </div>
    <div class="swiper-container mySwiper">
        <div class="swiper-wrapper">
            {% for post in posts %}
            <div class="swiper-slide">
                {% if post.thumbnail %}
                <img src="{{post.thumbnail.url}}">
                {% else %}
                <img src="http://www.billking.co.kr/index/skin/board/basic_support/img/noimage.gif">
                {% endif %}
                <h3>{{post.title}}</h3>
                <button type="button" onclick="location.href = '{% url 'list:feed_Detail' post.id%}';">내글보기</button>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="writeList">
    <div class="hTitleBox">
        <h2>근황 게시글</h2>
        <button type="button" class="writeBtn" onclick="location.href = '{% url 'user_info:recentWrite'%}';">작성하기
        </button>
    </div>
    <div class="swiper-container mySwiper">
        <div class="swiper-wrapper">
            {% for post in recent_posts %}
            <div class="swiper-slide">
                {% if post.photo %}
                <img src="{{post.photo.url}}">
                {% else %}
                <img src="http://www.billking.co.kr/index/skin/board/basic_support/img/noimage.gif">
                {% endif %}
                <h3>{{post.title}}</h3>
                <button type="button" onclick="location.href = '{% url 'user_info:recentDetail' post.id %}';">내글보기
                </button>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
</div>
<div class="footer">
    <ul>
        <li><a href="#" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="#" class="navItem">기업소개</a></li>
        <li><a href="#" class="navItem">이용약관</a></li>
        <li><a href="#" class="navItem">개인정보 처리방침</a></li>
        <li><a href="#" class="navItem">고객센터</a></li>
    </ul>
    <span class="line"></span>
    <h2>(주)후원트 (대표이사:후대표) | 대구광역시 수성구 범어천로20 두산위브더제니스 4202호 | 통신판매번호 : 00-00-00-00
        유료직업소개사업등록번호 : (국내) 제000-00000-00000 | (국외) 000-0000-0000 | 사업자등록번호 : 0000-0000-0000
        © WhoWantLab, Inc.</h2>
</div>

<script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
<script>
    var swiper = new Swiper(".mySwiper", {
        slidesPerView: 3,
        spaceBetween: 30,
        freeMode: true,
    });
</script>
</body>