HellProject/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from HellProject import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_info.urls'), name = 'user_info'),
    path('listview/', include('list.urls'), name='list'),
    path('inquiry/', include('inquiry.urls'), name='inquiry'),
    path('market/', include('market.urls'), name='market'),
]
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inquiry/urls.py
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'inquiry'

urlpatterns=[
    path('CS/', views.CS, name = 'CS'),
    path('FAQ/', views.FAQ, name = 'FAQ'),
]

list/urls.py
from django.urls import path
from django.conf.urls.static import static

from HellProject import settings
from . import views

app_name = 'list'

urlpatterns =[
    path('list_view/', views.list_view, name='list_view'),

    path('helpWrite/', views.helpWrite, name='helpWrite'),
    path('helpUpdate/<str:id>', views.helpUpdate, name='helpUpdate'),
    path('helpDelete/<str:id>', views.helpDelete, name='helpDelete'),
    
    path('feed_Deatil/<str:id>', views.feed_Detail, name='feed_Detail'),
    path('donate/<str:id1>/<str:id2>/<str:id3>', views.donate, name='donate'),
]

market/urls.py
from django.urls import path
from django.conf.urls.static import static

from HellProject import settings
from . import views

app_name = 'market'

urlpatterns =[
    path('', views.market_view, name='market_view'),
    path('marketDetail/<str:id>', views.market_Detail, name='market_Detail'),
    path('marketWrite/', views.market_Write, name='market_Write'),
    path('marketDelete/<str:id>', views.market_Delete, name='market_Delete'),
    path('marketUpdate/<str:id>',views.market_Update, name='market_Update'),
    path('comment/<str:id>',views.comment, name='comment'),
]

user_info/urls.py
from django.urls.conf import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'user_info'

urlpatterns=[
    path('', views.home, name = 'home'),
    path('mypage', views.mypage, name = 'mypage'),
    path('login', views.login_view, name = 'login_view'),
    path('signup', views.signup, name = 'signup'),
    path('logout_view/', views.logout_view, name="logout_view"),
    path('findID/', views.findID, name='findID'),
    path('delete/', views.delete, name = 'delete'),
    path('spon_delete/',views.spon_delete, name="spon_delete"),
    path('registerauth/', views.get_success_url, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),

    path('recovery/id/find/', views.ajax_find_id_view, name='ajax_id'),
    path('recovery/id/', views.RecoveryIdView.as_view(), name='recovery_id'),
    path('recovery/pw/', views.RecoveryPwView.as_view(), name='recovery_pw'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='recovery_pw_reset'),

    path('profile_view/', views.profile_view, name='profile_view'),
    path('profile_update_view/', views.profile_update_view, name='profile_update_view'),
    path('verify/', views.verify, name='verify'),
    path('sponserpage/', views.sponserpage, name="sponserpage"),

    path('recentView/<str:email>', views.recentView, name="recentView"),
    path('recentDetail/<str:id>', views.recentDetail, name='recentDetail'),
    path('recentWrite/', views.recentWrite, name="recentWrite"),
    path('recentWriteUpdate/<str:id>', views.recentWriteUpdate, name="recentWriteUpdate"),
    path('recentDelete/<str:id>', views.recentDelete, name="recentDelete"),    
]

market/models.py
from django.db import models
from user_info.models import CustomUser, UserInfo
from datetime import datetime, timedelta
from django.utils import timezone

# Create your models here.

class MarketPost(models.Model):
    id = models.BigAutoField(help_text="Post ID", primary_key=True)
    title = models.CharField(max_length=100)
    writer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='user')
    post_time = models.DateTimeField(auto_now_add=True, verbose_name="등록 시간")
    body = models.CharField(max_length=500)
    thumbnail = models.ImageField(verbose_name='썸네일', upload_to='market/', null=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.post_time

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days= 1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days= 7):
            time = datetime.now(tz=timezone.utc).date() - self.post_time.date()
            return str(time.days) + '일 전'
        else:
            return False

class Comment(models.Model):
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    post = models.ForeignKey(MarketPost, on_delete=models.CASCADE, related_name="posts")
    body = models.CharField(max_length=30, blank=False)
    date = models.DateTimeField(auto_now_add=True, verbose_name="registe time")

    @property
    def created_string(self):
        time = datetime.now(tz=timezone.utc) - self.date

        if time < timedelta(minutes=1):
            return '방금 전'
        elif time < timedelta(hours=1):
            return str(int(time.seconds / 60)) + '분 전'
        elif time < timedelta(days= 1):
            return str(int(time.seconds / 3600)) + '시간 전'
        elif time < timedelta(days= 7):
            time = datetime.now(tz=timezone.utc).date() - self.date.date()
            return str(time.days) + '일 전'
        else:
            return False

market/views.py
from django.contrib.auth.backends import RemoteUserBackend
from user_info.models import CustomUser, UserInfo
from django.core import paginator
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from .models import MarketPost, Comment
from django.utils import timezone
from django.core.paginator import Paginator

# Create your views here.

def market_view(request):
    msg = ""
    if not request.user.is_authenticated:
        msg = 'Not_auth'
    elif not request.user.active:
        msg = "email_auth_error"
    post = MarketPost.objects.all().order_by('-id')
    paginator = Paginator(post, 3)
    page = request.GET.get('page')
    post = paginator.get_page(page)

    return render(request, 'market.html', {'posts':post, 'msg':msg})

from django.shortcuts import get_object_or_404

def market_Detail(request,id):
    post = MarketPost.objects.get(id=id)
    user_info = UserInfo.objects.get(user_email = request.user)
    comments = Comment.objects.filter(post=post)    

    return render(request, 'marketDetail.html', {"comments":comments, 'post':post, "user_info" : user_info})

@csrf_exempt
def market_Write(request):
    if request.method == 'POST':
        post = MarketPost()
        post.title = request.POST.get('title')
        print(request.user)
        post.writer = request.user
        post.post_time = timezone.now()
        post.body = request.POST.get('body')
        post.thumbnail = request.FILES.get('image')
        post.save()
        return redirect('market:market_view')
    return render(request, 'marketWrite.html')

def market_Delete(request, id):
    post = MarketPost.objects.get(id=id)
    post.delete()
    return redirect('market:market_view')

def market_Update(request, id):
    post = MarketPost.objects.get(id=id)
    if request.method == 'POST':
        post.title = request.POST['title']
        post.body = request.POST['body']
        post.post_time = timezone.now()
        post.thumbnail = request.FILES.get('image')
        post.save()
        return redirect('market:market_view')
    return render(request, 'marketUpdate.html', {'post':post})

def comment(request, id):
    if request.method == 'POST':
        comment = Comment.objects.create(
            user = UserInfo.objects.get(user_email=request.user.email),
            post = get_object_or_404(MarketPost, pk = id),
            body = request.POST.get('comment'),
            date = timezone.now(),
        )

    return redirect('market:market_Detail', id)

market/templates/market.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'market.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>후원을 다이렉트로, 후원트</title>
</head>
<body>
{% if not user.is_authenticated %}
    <script>
      alert("로그인 후 이용가능합니다!")
      window.location.href = "{% url 'user_info:login_view' %}"
    </script>
{% elif msg == 'email_auth_error' %}
    <script>
      alert("이메일 인증후 이용가능합니다!")
      window.location.href = "{% url 'user_info:mypage' %}"
    </script>
{% endif %}
<div class="header">
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
            <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>

<div class="contentBox">
    <div class="makeDonate">
        <div class="donate">
        <i class="fa fa-plus-circle" aria-hidden="true"></i>
        </div>
        <div class="verticalTextBox">
            <h2>도움을 주고싶나요?</h2>
            <h3>내가 가진 재능을 다른사람에게 공유해 주세요!</h3>
        </div>
    </div>
    {% for post in posts %}
        <div class="content">
            <div class="title">
                <i class="fa fa-user-circle" aria-hidden="true"></i>
                <div class="titleTextBox">
                    <h2 class="userName">{{ post.writer }}</h2>
                    <h3 class="time">
                        {% if post.created_string == False %}
                            {{ post.created|date:'m월 d일' }}
                        {% else %}
                            {{ post.created_string }}
                        {% endif %}
                    </h3>
                </div>
            </div>
            <h2> {{post.title}} </h2>
            <h2 class="contents">{{ post.body }}</h2>
            {% if post.thumbnail %}
                <div class="imgBox">
                    <img class="contentImg" src="{{ post.thumbnail.url }}">
                </div>
            {% endif %}
            <div class="btnBox">
                <button type="button" onclick="location.href='{% url 'market:market_Detail' post.id %}'">더 알아보기 >>
                </button>
            </div>
        </div>
    {% endfor %}
    <div class="pager">
        <div class="pagerBox">
            <!-- 이전 페이지가 있을때만 보이도록 -->
            {% if posts.has_previous %}
                <a href="?page=1">처음</a>
                <a href="?page={{ posts.previous_page_number }}">이전</a>
            {% endif %}
            <!-- 현재 몇번째 페이지인지 -->
            <span>{{ posts.number }}</span>
            <span>of</span>
            <span>{{ posts.paginator.num_pages }}</span>
            <!-- 다음 페이지가 있을때만 보이도록 -->
            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">다음</a>
                <a href="?page={{ posts.paginator.num_pages }}">마지막</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="footer">
    <ul>
        <li><a href="#" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="#" class="navItem">기업소개</a></li>
        <li><a href="#" class="navItem">이용약관</a></li>
        <li><a href="#" class="navItem">개인정보 처리방침</a></li>
        <li><a href="#" class="navItem">고객센터</a></li>
    </ul>
    <span class="line"></span>
    <h2>(주)후원트 (대표이사:후대표) | 대구광역시 수성구 범어천로20 두산위브더제니스 4202호 | 통신판매번호 : 00-00-00-00
        유료직업소개사업등록번호 : (국내) 제000-00000-00000 | (국외) 000-0000-0000 | 사업자등록번호 : 0000-0000-0000
        © WhoWantLab, Inc.</h2>
</div>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(".donate").click(function () {
        $(location).attr("href", "{% url 'market:market_Write' %}");
    });
</script>
</body>
</html>

market/templates/marketDetail.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <script> function press(f) {
        if (f.keyCode == 13) {
            formname.submit("form");
        }
    }
    </script>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'marketDetail.css'%}">
    <link rel="stylesheet" type="text/css" href="../../static/marketDetail.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>후원을 다이렉트로, 후원트</title>
</head>
<body>
<div class="header">
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
        <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
        <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>

<div class="contentBox">
    <div class="makeDonate">
        <!--    <i class="fa fa-plus-circle" aria-hidden="true"></i>-->
        <img src="{% static '/img/logo.png' %}">
        <div class="verticalTextBox">
            <h2>해당 재능이 필요하신가요?</h2>
            <h3>재능마켓에서 재능을 요청해 보세요!</h3>
        </div>
    </div>
    <div class="content">
        <div class="title">
            <i class="fa fa-user-circle" aria-hidden="true"></i>
            <div class="titleTextBox">
                <h2 class="userName">{{post.writer}}</h2>
                <h3 class="time">
                    {% if post.created_string == False %}
                    {{post.created|date:'m월 d일'}}
                    {% else %}
                    {{post.created_string}}
                    {% endif %}
                </h3>
            </div>
        </div>
        <h2> {{post.title}} </h2>
        <h2 class="contents">{{post.body}}</h2>
        <div class="imgBox">
            {% if post.thumbnail %}
            <img style="width: 40%;" class="contentImg" src="{{post.thumbnail.url}}">
            {% endif %}
        </div>
        {% if post.writer == user%}
        <div class="btnBox">
            <button class="writeBtn" type="button" onclick="location.href = '{% url 'market:market_Update' post.id%}'">
                수정하기
            </button>
            <button class="writeBtn" type="button" onclick="location.href = '{% url 'market:market_Delete' post.id%}'">
                삭제하기
            </button>
        </div>
        {% endif %}
        <div class="line"></div>
        <form action="{% url 'market:comment' post.id %}" method='POST' name="form">
            {% csrf_token %}
            <div class="inputArea">
                <!--        <i class="fa fa-user-circle-o" aria-hidden="true"></i>-->
                {% if user_info.user_image %}
                <img src="{{user_info.user_image.url}}" class="userImg">
                {% else %}
                <img src="{% static 'img/original.png'%}" class="userImg">
                {% endif %}
                <input type="text" class="commentInput" placeholder="댓글을 입력하세요.."
                       onkeypress="JavaScript:press(this.form)" name="comment">
            </div>
        </form>
        {% for comment in comments %}
        <div class="commentArea">
            <div class="commentBox">
                <div class="horizontalBox">
                    <!--        <i class="fa fa-user-circle-o" aria-hidden="true"></i>-->
                    <div class="verticalTextBox">
                        {% if comment.user.user_image %}
                        <img src="{{comment.user.user_image.url}}" class="userImg">
                        {% else %}
                        <img src="{% static 'img/original.png' %}" class="userImg">
                        {% endif %}
                        <h2>{{comment.user.user_nickname}}</h2>
                    </div>
                    <div class="horizontalBox">
                        <div class="comment">{{ comment.body }}</div>
                        {% if comment.created_string == False %}
                        <h2>{{ comment.created|date:'m월 d일' }}</h2>
                        {% else %}
                        <h2>{{ comment.created_string }}</h2>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="footer">
    <ul>
        <li><a href="#" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="#" class="navItem">기업소개</a></li>
        <li><a href="#" class="navItem">이용약관</a></li>
        <li><a href="#" class="navItem">개인정보 처리방침</a></li>
        <li><a href="#" class="navItem">고객센터</a></li>
    </ul>
    <span class="line"></span>
    <h2>(주)후원트 (대표이사:후대표) | 대구광역시 수성구 범어천로20 두산위브더제니스 4202호 | 통신판매번호 : 00-00-00-00
        유료직업소개사업등록번호 : (국내) 제000-00000-00000 | (국외) 000-0000-0000 | 사업자등록번호 : 0000-0000-0000
        © WhoWantLab, Inc.</h2>
</div>
</body>
</html>

market/templates/marketUpdate.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'marketWrite.css'%}">
    <title>재능 마켓 작성</title>
</head>
<body>
<div class="header">
    {% if not user.is_authenticated %}
        <script>
            alert("로그인 후 이용해주세요");
            window.location.href = "{% url 'user_info:login_view' %}";
        </script>
    {% endif %}
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
            <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>
<div class="inputArea">
    <h2>재능 마켓 게시글 작성</h2>
    <form action='{% url 'market:market_Update' post.id %}' method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        <table class="text-box">
            <tr class="top">
                <td class="first"><p>제목</p></td>
                <td><textarea name="title" class="title">{{post.title}}</textarea></td>
            </tr>
            <tr>
                <td class="first"><p>파일</p></td>
                <td><input class="img" name='image' type="file" multiple></td>
            </tr>
            <tr class="bottom">
                <td class="first"><p>내용</p></td>
                <td class="content"><textarea name="body"  class="formText">{{post.body}}</textarea></td>
            </tr>
        </table>
        <table class="button-box">
            <tr>
                <td><input type="submit" value="제출하기" class="csSubmit"></td>
                <td><input type="submit" value="목록보기" class="csList"></td>
            </tr>
        </table>
    </form>
</div>
</body>
</html>

market/templates/marketWrite.html
<!doctype html>
{% load static %}
<html lang="kor">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'marketWrite.css'%}">
    <title>재능 마켓 작성</title>
</head>
<body>
<div class="header">
    {% if not user.is_authenticated %}
        <script>
            alert("로그인 후 이용해주세요");
            window.location.href = "{% url 'user_info:login_view' %}";
        </script>
    {% endif %}
    <ul>
        <li><a href="{% url 'user_info:home' %}" class="logo">WHO<span>WANT</span></a></li>
        <li><a href="{% url 'list:helpWrite' %}" class="navItem">후원받기</a></li>
        <li><a href="{% url 'market:market_view' %}" class="navItem">재능마켓</a></li>
        <li><a href="{% url 'inquiry:CS' %}" class="navItem">문의하기</a></li>
        <li><a href="{% url 'inquiry:FAQ' %}" class="navItem">FAQ</a></li>
        <li><a href="{% url 'user_info:mypage' %}" class="navItem">마이페이지</a></li>
        {% if not user.is_authenticated %}
            <li><a href="{% url 'user_info:login_view' %} " class="navItem">Login</a></li>
        {% else %}
            <li><a href="{% url 'user_info:logout_view' %}" class="navItem">Logout</a></li>
        {% endif %}
    </ul>
</div>
<div class="inputArea">
    <div class="title-box">
        <h2>재능 마켓 게시글 작성</h2>
    </div>

    <form action='{% url 'market:market_Write'%}' method='POST' enctype='multipart/form-data'>
        {% csrf_token %}
        <table class="text-box">
            <tr class="top">
                <td class="first"><p>제목</p></td>
                <td><textarea name="title" class="title"></textarea></td>
            </tr>
            <tr>
                <td class="first"><p>파일</p></td>
                <td><input class="img" name='image' type="file" multiple></td>
            </tr>
            <tr class="bottom">
                <td class="first"><p>내용</p></td>
                <td class="content"><textarea name="body"  class="formText"></textarea></td>
            </tr>
        </table>
        <table class="button-box">
            <tr>
                <td><input type="submit" value="제출하기" class="csSubmit"></td>
                <td><input type="submit" value="목록보기" class="csList"></td>
            </tr>
        </table>
        
        
        
    </form>
</div>
</body>
</html>